# Generated by Django 2.2 on 2021-05-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='use_profile',
            new_name='user_profile',
        ),
    ]
